### ISSUE TITLE
Automatic model reliability uptating for engines at full condition or from saved ships

### ISSUE THREAD

**Issue by DarthPointer** [DarthPointer/PayToPlay#25]
Needs a way to tell whether the part is loaded via KCT-edit vessel or stockish loading ship/from part menu. Waiting for @LinuxGuruGamer to give me some help as I can't find a way to do it without changing KCT souces and my MVS fails to build KCT.

// If I get no response I'll look for the solution on my own

**Comment by linuxgurugamer** [comment]
Assuming MVS = Microsoft Visual Studio, you probably need to update the references.
Note that the project files I use rely on an environment variable KSPDIR pointing to the destination KSP directory.  It needs to be set before you log on to Windows

**Comment by DarthPointer** [comment]
![изображение](https://user-images.githubusercontent.com/48957477/85920033-f38e5880-b878-11ea-9802-7c358a434463.png)
Well... This is the error message of my Microsoft Visual Studio. I use MVS 2019 and have right the same folder with the .exe it fails to find, but with folder 2019 instead of 2017 (not a surprize). Where do I change it?

Upd: all KSP and KSP mods' .dlls are manually linked by me, it is just a matter of the project thinking it is opened in a 2017 MVS.

**Comment by DarthPointer** [comment]
Upd: I have successfully built KCT with a new project using copied files. No deviations detected (yet).
